import { images } from "../assets";
import { ROUTES } from "../utils/routes";

const sharedAdminProfile = {
  name: "Admin Curator",
  role: "Administrator",
  avatar: null,
};

export const layoutContent = {
  [ROUTES.dashboard]: {
    breadcrumb: "Dashboard",
    sidebarProfile: sharedAdminProfile,
    sidebarSubtitle: "Admin Curator",
    topbarProfile: null,
    topbarSearchPlaceholder: "",
  },
  [ROUTES.tours]: {
    breadcrumb: "Tours",
    sidebarProfile: sharedAdminProfile,
    sidebarSubtitle: "Admin Curator",
    topbarProfile: null,
    topbarSearchPlaceholder: "",
  },
  [ROUTES.newTour]: {
    breadcrumb: "Create Tour",
    sidebarProfile: sharedAdminProfile,
    sidebarSubtitle: "Admin Curator",
    topbarProfile: null,
    topbarSearchPlaceholder: "",
  },
  [ROUTES.bookings]: {
    breadcrumb: "Bookings",
    sidebarProfile: sharedAdminProfile,
    sidebarSubtitle: "Admin Curator",
    topbarProfile: null,
    topbarSearchPlaceholder: "",
  },
  [ROUTES.users]: {
    breadcrumb: "Users",
    sidebarProfile: sharedAdminProfile,
    sidebarSubtitle: "Admin Curator",
    topbarProfile: null,
    topbarSearchPlaceholder: "Search user by name or email...",
  },
  [ROUTES.reviews]: {
    breadcrumb: "Reviews",
    sidebarProfile: sharedAdminProfile,
    sidebarSubtitle: "Admin Curator",
    topbarProfile: null,
    topbarSearchPlaceholder: "",
  },
  [ROUTES.payments]: {
    breadcrumb: "Payments",
    sidebarProfile: sharedAdminProfile,
    sidebarSubtitle: "Admin Curator",
    topbarProfile: null,
    topbarSearchPlaceholder: "",
  },
};

export function getLayoutContent(pathname) {
  return layoutContent[pathname] ?? layoutContent[ROUTES.dashboard];
}

export const dashboardPage = {
  title: "The Horizon - Admin Dashboard",
  summaryCards: [
    {
      id: "total-tours",
      icon: "explore",
      label: "Total Tours",
      value: "128",
      iconPanelClassName: "bg-primary/10 text-primary",
      badge: "+12%",
      badgeClassName: "bg-emerald-50 text-emerald-600",
    },
    {
      id: "active-bookings",
      icon: "calendar_month",
      label: "Active Bookings",
      value: "452",
      iconPanelClassName: "bg-secondary-container/30 text-primary",
      badge: "+24%",
      badgeClassName: "bg-emerald-50 text-emerald-600",
    },
    {
      id: "new-users",
      icon: "group",
      label: "New Users",
      value: "1.2k",
      iconPanelClassName: "bg-tertiary-fixed/30 text-tertiary",
      badge: "+8.5%",
      badgeClassName: "bg-emerald-50 text-emerald-600",
    },
    {
      id: "revenue",
      icon: "payments",
      label: "Monthly Revenue",
      value: "$84,200",
      iconPanelClassName: "bg-emerald-100 text-emerald-700",
      badge: "+32%",
      badgeClassName: "bg-emerald-50 text-emerald-600",
    },
  ],
  chartTabs: [
    { key: "weekly", label: "Weekly" },
    { key: "monthly", label: "Monthly" },
  ],
  chartData: {
    weekly: [
      { label: "Mon", height: 132 },
      { label: "Tue", height: 174 },
      { label: "Wed", height: 150 },
      { label: "Thu", height: 198 },
      { label: "Fri", height: 226, secondary: true },
      { label: "Sat", height: 246, active: true },
    ],
    monthly: [
      { label: "Jan", height: 96 },
      { label: "Feb", height: 128 },
      { label: "Mar", height: 192 },
      { label: "Apr", height: 160 },
      { label: "May", height: 224, secondary: true },
      { label: "Jun", height: 256, active: true },
    ],
  },
  recentBookings: [
    {
      id: "#HZ-9842",
      initials: "EK",
      initialsClassName: "bg-blue-100 text-primary",
      customer: "Elena Kovic",
      tour: "Amalfi Coast Sunset",
      date: "Oct 12, 2023",
      amount: "$1,250",
      status: "Confirmed",
      statusTone: "success",
    },
    {
      id: "#HZ-9843",
      initials: "JM",
      initialsClassName: "bg-amber-100 text-amber-700",
      customer: "James Miller",
      tour: "Kyoto Bamboo Forest",
      date: "Oct 14, 2023",
      amount: "$890",
      status: "Pending",
      statusTone: "pending",
    },
    {
      id: "#HZ-9844",
      initials: "ST",
      initialsClassName: "bg-slate-100 text-slate-600",
      customer: "Sarah Tan",
      tour: "Iceland Northern Lights",
      date: "Oct 15, 2023",
      amount: "$2,100",
      status: "Confirmed",
      statusTone: "success",
    },
  ],
};

export const toursPage = {
  title: "Quan ly Tour",
  description:
    "Curate and manage premium travel experiences for The Horizon travelers worldwide.",
  rows: [
    {
      id: "TR-8829",
      name: "Du thuyen Vinh Ha Long Luxury",
      image: images.tourHaLong,
      location: "Quang Ninh, VN",
      duration: "3 Days, 2 Nights",
      price: "4,500,000d",
      status: "Active",
    },
    {
      id: "TR-3421",
      name: "Cao nguyen Da Lat tho mong",
      image: images.tourDaLat,
      location: "Lam Dong, VN",
      duration: "2 Days, 1 Night",
      price: "2,200,000d",
      status: "Active",
    },
    {
      id: "TR-0012",
      name: "Nha Trang Bien Goi Summer",
      image: images.tourNhaTrang,
      location: "Khanh Hoa, VN",
      duration: "4 Days, 3 Nights",
      price: "6,800,000d",
      status: "Draft",
    },
    {
      id: "TR-9941",
      name: "Tay Bac Mua Lua Chin",
      image: images.tourSapa,
      location: "Lao Cai, VN",
      duration: "3 Days, 2 Nights",
      price: "3,900,000d",
      status: "Active",
    },
  ],
  summaryCards: [
    {
      id: "total",
      icon: "inventory_2",
      label: "Total Tours",
      value: "128",
      iconPanelClassName: "bg-white text-blue-600 shadow-sm",
      className: "bg-surface-container-low border-none rounded-3xl",
    },
    {
      id: "active",
      icon: "check_circle",
      label: "Active Tours",
      value: "94",
      iconPanelClassName: "bg-white text-green-600 shadow-sm",
      className: "bg-surface-container-low border-none rounded-3xl",
    },
  ],
  tip: {
    label: "Curation Tip",
    title: "Add more eco-tours in Central Vietnam. High demand for Q3!",
  },
};

export const bookingsPage = {
  title: "Bookings Management",
  description: "Oversee all traveler expeditions and reservation statuses.",
  stats: [
    { id: "total", label: "Total Bookings", value: "1,284", meta: "+12%", metaClassName: "text-green-600" },
    { id: "pending", label: "Pending", value: "42", meta: "Requires action", metaClassName: "text-tertiary" },
    { id: "confirmed", label: "Confirmed", value: "1,108", meta: "This year", metaClassName: "text-slate-400" },
    { id: "revenue", label: "Revenue", value: "$248.5k", meta: "Gross", metaClassName: "text-primary" },
  ],
  rows: [
    {
      id: "#HZ-88219",
      customer: "Elena Kovic",
      email: "elena.k@example.com",
      initials: "EK",
      initialsClassName: "bg-primary-fixed text-on-primary-fixed-variant",
      tour: "Santorini Sunset Sailing",
      subtitle: "Private Catamaran",
      travelDate: "Oct 12, 2023",
      total: "$1,240.00",
      status: "Confirmed",
      statusTone: "success",
    },
    {
      id: "#HZ-88220",
      customer: "Julian Moore",
      email: "j.moore@travel.net",
      initials: "JM",
      initialsClassName: "bg-tertiary-fixed text-on-tertiary-fixed",
      tour: "Swiss Alps Peak Explorer",
      subtitle: "Group Guided Tour",
      travelDate: "Nov 05, 2023",
      total: "$2,100.00",
      status: "Pending",
      statusTone: "pending",
    },
    {
      id: "#HZ-88221",
      customer: "Sarah Jenkins",
      email: "sarah.j@global.com",
      avatar: images.bookingsCustomerSarah,
      tour: "Kyoto Temple Garden Walk",
      subtitle: "Cultural Immersion",
      travelDate: "Oct 29, 2023",
      total: "$450.00",
      status: "Cancelled",
      statusTone: "blocked",
    },
    {
      id: "#HZ-88222",
      customer: "Mark Thompson",
      email: "m.thompson@gmail.com",
      initials: "MT",
      initialsClassName: "bg-secondary-container text-on-secondary-container",
      tour: "Iceland Glacial Trek",
      subtitle: "Extreme Adventure",
      travelDate: "Dec 15, 2023",
      total: "$3,400.00",
      status: "Confirmed",
      statusTone: "success",
    },
    {
      id: "#HZ-88223",
      customer: "Lisa Park",
      email: "lisa.park@example.com",
      initials: "LP",
      initialsClassName: "bg-slate-200 text-slate-600",
      tour: "Safari Serenity Kenya",
      subtitle: "Luxury Safari",
      travelDate: "Jan 10, 2024",
      total: "$5,200.00",
      status: "Pending",
      statusTone: "pending",
    },
  ],
  insight: {
    title: "Upcoming High-Volume Season",
    description:
      "Our analytics predict a 40% increase in bookings for European destinations this November. Consider reviewing guide availability and updating confirmation workflows.",
    actionLabel: "View Forecast Details",
    image: images.bookingsHeroBeach,
  },
};

export const usersPage = {
  title: "User Management | The Horizon Admin",
  stats: [
    {
      id: "total-users",
      label: "Total Users",
      value: "12,842",
      detail: "8% vs last month",
      detailTone: "text-green-600",
    },
    {
      id: "active-now",
      label: "Active Now",
      value: "1,402",
      avatars: [images.usersActive1, images.usersActive2, images.usersActive3],
    },
    {
      id: "pending-verifications",
      label: "Pending Verifications",
      value: "42",
      detail: "Needs attention",
      detailTone: "text-amber-600",
    },
    {
      id: "blocked-accounts",
      label: "Blocked Accounts",
      value: "12",
      detail: "Compliance flagged",
      detailTone: "text-slate-400",
    },
  ],
  rows: [
    {
      id: "marcus-ardelio",
      name: "Marcus Ardelio",
      email: "marcus.a@horizon.com",
      avatar: images.usersMarcus,
      role: "Admin",
      roleTone: "admin",
      status: "Active",
      statusTone: "success",
      registeredAt: "Oct 12, 2023",
      actionLabel: "Block",
    },
    {
      id: "elena-vance",
      name: "Elena Vance",
      email: "elena.v@gmail.com",
      avatar: images.usersElena,
      role: "User",
      roleTone: "user",
      status: "Active",
      statusTone: "success",
      registeredAt: "Nov 04, 2023",
      actionLabel: "Block",
    },
    {
      id: "julian-stark",
      name: "Julian Stark",
      email: "j.stark@outlook.com",
      avatar: images.usersJulian,
      role: "User",
      roleTone: "user",
      status: "Blocked",
      statusTone: "blocked",
      registeredAt: "Dec 20, 2023",
      actionLabel: "Unblock",
    },
    {
      id: "lila-thorne",
      name: "Lila Thorne",
      email: "lila.t@thehorizon.travel",
      avatar: images.usersLila,
      role: "Admin",
      roleTone: "admin",
      status: "Active",
      statusTone: "success",
      registeredAt: "Jan 15, 2024",
      actionLabel: "Block",
    },
    {
      id: "aaron-patel",
      name: "Aaron Patel",
      email: "apatel@gmail.com",
      avatar: images.usersAaron,
      role: "User",
      roleTone: "user",
      status: "Inactive",
      statusTone: "inactive",
      registeredAt: "Feb 02, 2024",
      actionLabel: "Block",
    },
  ],
};

export const reviewsPage = {
  title: "Review Moderation",
  stats: [
    { id: "total", label: "Total Reviews", value: "1,482" },
    { id: "avg", label: "Avg Rating", value: "4.8" },
    { id: "needs-action", label: "Needs Action", value: "57" },
    { id: "approved", label: "Approved Today", value: "12" },
  ],
  filterOptions: ["All Pending", "1-2 Stars", "Reported", "By Tour"],
  rows: [
    {
      id: "julianne-davis",
      name: "Julianne Davis",
      date: "October 14, 2023",
      rating: 5,
      tour: "Santorini Sunset Escape",
      content:
        "The experience was absolutely breathtaking. The guide was knowledgeable and the pace was perfect. I highly recommend this to anyone visiting Greece for the first time. The boat ride back during sunset was the highlight!",
      avatar: images.reviewsJulianne,
      reported: false,
    },
    {
      id: "mark-kovacs",
      name: "Mark Kovacs",
      date: "October 12, 2023",
      rating: 2,
      tour: "Tokyo Night Market Tour",
      content:
        "The tour was okay, but the group size was way too large. We could not hear the guide half the time and felt rushed between stalls. Needs better management for the price paid.",
      avatar: images.reviewsMark,
      reported: true,
    },
    {
      id: "sarah-lee",
      name: "Sarah Lee",
      date: "October 11, 2023",
      rating: 5,
      tour: "Swiss Alps Glacier Hike",
      content:
        "Simply magical. Every detail was handled by The Horizon. I have never felt so taken care of on an adventure trip. The local cheese tasting was a wonderful surprise!",
      avatar: images.reviewsSarah,
      reported: false,
    },
    {
      id: "alex-martinez",
      name: "Alex Martinez",
      date: "October 10, 2023",
      rating: 4,
      tour: "Barcelona Tapas Crawl",
      content:
        "Loved the food! The only reason for 4 stars is that one of the restaurants was closed so we had to skip a stop, but the guide compensated with extra wine at the next place.",
      avatar: images.reviewsAlex,
      reported: false,
    },
  ],
};

export const paymentsPage = {
  title: "Payments & Transactions | The Horizon Admin",
  hero: {
    label: "Total Treasury Balance",
    value: "$142,850.24",
  },
  summaryCards: [
    {
      id: "today",
      icon: "trending_up",
      iconPanelClassName: "bg-tertiary-fixed text-tertiary",
      label: "Today's Revenue",
      value: "$12,450.00",
      badge: "+12.4%",
      badgeClassName: "bg-emerald-50 text-emerald-600",
      footer: "Updated 2 mins ago",
    },
    {
      id: "pending",
      icon: "pending_actions",
      iconPanelClassName: "bg-secondary-container text-secondary",
      label: "Pending Payouts",
      value: "$3,120.50",
      badge: "8 Tasks",
      badgeClassName: "bg-slate-100 text-slate-500",
      progress: 65,
    },
  ],
  transactions: [
    {
      id: "TXN-8821094",
      bookingId: "#HOR-2210",
      customer: "Elena Mitsis",
      initials: "EM",
      initialsClassName: "bg-blue-100 text-blue-700",
      method: "Visa ending in 4421",
      methodIcon: images.paymentsVisaLogo,
      date: "Oct 24, 2023 • 14:22",
      amount: "$1,450.00",
      status: "Success",
      statusTone: "success",
    },
    {
      id: "TXN-8821095",
      bookingId: "#HOR-2211",
      customer: "Julian DeSilva",
      initials: "JD",
      initialsClassName: "bg-amber-100 text-amber-700",
      method: "MoMo Wallet",
      methodTone: "momo",
      date: "Oct 24, 2023 • 15:45",
      amount: "$680.00",
      status: "Pending",
      statusTone: "pending",
    },
    {
      id: "TXN-8821096",
      bookingId: "#HOR-2212",
      customer: "Sarah Ahmed",
      initials: "SA",
      initialsClassName: "bg-purple-100 text-purple-700",
      method: "Direct Bank Transfer",
      methodTone: "bank",
      date: "Oct 24, 2023 • 16:10",
      amount: "$2,200.00",
      status: "Failed",
      statusTone: "failed",
    },
    {
      id: "TXN-8821097",
      bookingId: "#HOR-2215",
      customer: "Mark Kovac",
      initials: "MK",
      initialsClassName: "bg-slate-100 text-slate-700",
      method: "Mastercard ending in 0019",
      methodIcon: images.paymentsMastercardLogo,
      date: "Oct 25, 2023 • 09:12",
      amount: "$410.00",
      status: "Success",
      statusTone: "success",
    },
  ],
};
